export const cartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  TOGGLE_SIGNIN: "TOGGLE_SIGNIN",
  TOGGLE_SIGNOUT: "TOGGLE_SIGNOUT",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
};
